### ISSUE TITLE
Background colour isn't entirely controllable

### ISSUE THREAD

**Issue by lumotroph** [hinodi/react-native-animated-circular-progress#2]
Thanks for the excellent work so far!

Normally the component looks great, but applying a background colour (via the `style` property) doesn't seem to properly affect the background colour of the center of the element:
![image](https://user-images.githubusercontent.com/12592541/91842205-ecf2d780-ec53-11ea-9c41-dce36d867d95.png)
For example, in this image, I've set the background colour to `#FF0000` and chosen a green colour for the `style` property.

The background element here which creates the white circle lies under the three `AnimatedComponents` (see green arrow in diagram). The colour of this element is set in an unreachable part of the component and cannot be edited via props (at least I can't seem to see where to change it 😓 ). The style property which can be fed to the component actually affects only the first RCTView component (see red arrow in diagram) - and changing that background colour (on the first RCTView) doesn't change the background colour we need (on the second RCTView).

See diagram:
![image](https://user-images.githubusercontent.com/12592541/91842374-393e1780-ec54-11ea-8160-1775e35507df.png)

**Comment by hinodi** [comment]
> Thanks for the excellent work so far!
> 
> Normally the component looks great, but applying a background colour (via the `style` property) doesn't seem to properly affect the background colour of the center of the element:
> ![image](https://user-images.githubusercontent.com/12592541/91842205-ecf2d780-ec53-11ea-9c41-dce36d867d95.png)
> For example, in this image, I've set the background colour to `#FF0000` and chosen a green colour for the `style` property.
> 
> The background element here which creates the white circle lies under the three `AnimatedComponents` (see green arrow in diagram). The colour of this element is set in an unreachable part of the component and cannot be edited via props (at least I can't seem to see where to change it 😓 ). The style property which can be fed to the component actually affects only the first RCTView component (see red arrow in diagram) - and changing that background colour (on the first RCTView) doesn't change the background colour we need (on the second RCTView).
> 
> See diagram:
> ![image](https://user-images.githubusercontent.com/12592541/91842374-393e1780-ec54-11ea-8160-1775e35507df.png)

already fixed from version 1.0.6
you can use `innerBackgroundColor` props to config inner circle

**Comment by hinodi** [comment]
already fixed from version 1.0.6
you can use `innerBackgroundColor` props to config inner circle
